repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: cargo-check
        args: ["--workspace"]
        stages: ["pre-commit"]
    -   id: fmt
        args: ["--", "--check"]
        stages: ["pre-commit"]
    -   id: clippy
        args: ["--", "-D", "warnings"]
        stages: ["pre-commit"]
